### ISSUE TITLE
Stylelint のセットアップ

### ISSUE THREAD

**Issue by knokmki612** [tuqulore/jumpu-ui#421]

**Comment by Hidetaro7** [comment]
解決策を模索する必要があるので、優先度を下げるため、まだやらないへ移行。

**Comment by knokmki612** [comment]
> postcss-js との組み合わせで動作しなかった。
> 関連？: https://github.com/postcss/postcss/issues/1767
> 関連？: [StylelintでCSS-in-JSをlintする時にハマったこと](https://zenn.dev/cp20/articles/2844af357345cf#%E5%8F%82%E8%80%83)
> 
> ```
> $ yarn stylelint tab.js
> yarn run v1.22.22
> $ /var/home/kimiaki/Workspace/github.com/tuqulore/jumpu-ui/node_modules/.bin/stylelint tab.js
> TypeError: Cannot read properties of undefined (reading 'stringify')
>     at LazyResult.stringify (/var/home/kimiaki/Workspace/github.com/tuqulore/jumpu-ui/node_modules/postcss/lib/lazy-result.js:347:13)
>     at LazyResult.runAsync (/var/home/kimiaki/Workspace/github.com/tuqulore/jumpu-ui/node_modules/postcss/lib/lazy-result.js:308:17)
>     at LazyResult.async (/var/home/kimiaki/Workspace/github.com/tuqulore/jumpu-ui/node_modules/postcss/lib/lazy-result.js:160:30)
>     at LazyResult.then (/var/home/kimiaki/Workspace/github.com/tuqulore/jumpu-ui/node_modules/postcss/lib/lazy-result.js:404:17)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> _Originally posted by @knokmki612 in https://github.com/tuqulore/jumpu-ui/pull/618#discussion_r1797287744_

**Comment by knokmki612** [comment]
Tailwind CSS v4 では CSS-in-JS でコンポーネントを書く必要がなくなっている。

したがってカスタムパーサーもいらないはず。

**Comment by knokmki612** [comment]
https://github.com/tuqulore/jumpu-ui/pull/665 にて導入済み。

> 使用しないプロパティを指定 https://stylelint.io/user-guide/rules/property-disallowed-list/

こちらは未導入

**Comment by knokmki612** [comment]
つづきは #387 で
